codefirst/FlickSKK

FlickSKK/WordRegisterViewController.swift

* 一部フィールドのみ入力されている場合の挙動の整理
* 読みに漢字が入った場合 (辞書的には問題ないかもしれない)
* おくりに漢字が入った場合 (子音に変換できていない)

設定アプリの単語登録の異常系ハンドリング

---

FlickSKKKeyboard/ComposeModePresenter.swift
FlickSKKTests/ComposeModePresenterSpec.swift

>  banjun commented 2 hours ago
> これアグレッシブ候補表示 #18 の初期状態(候補選択されていない状態)でも表示してほしいです。
> https://github.com/codefirst/FlickSKK/issues/61#issuecomment-74375144
の対応です。

▽モードでもスペースキーのかわりに「次候補」を出すようにした

---

FlickSKKKeyboard/KeyHandler.swift
FlickSKKTests/KeyHandlerSpec.swift

* ▽へんなはなし
* space
* 「変」を選択状態にして「な」入力
↓
「変」が登録モードに入力され，「な」が直接入力されてしまう。登録モードに入力されるべき。

登録モードで変換候補選択状態からの次単語入力が，登録モードではなく直接入力されてしまう

---

FlickSKK.xcodeproj/project.pbxproj
FlickSKK/Appearance.swift
FlickSKK/WordRegisterViewController.swift
FlickSKKKeyboard/KeyButton.swift
FlickSKKKeyboard/KeyButtonFlickPopup.swift
FlickSKKKeyboard/SessionView.swift

シミュレータでの表示改善です。 もしくはスクリーンショット撮影用(#80)。

システムフォントではなくヒラギノ角ゴシックを使うようにした

---

FlickSKK.xcodeproj/project.pbxproj
Memo/AppDelegate.swift
Memo/Base.lproj/LaunchScreen.xib
Memo/Images.xcassets/AppIcon.appiconset/Contents.json
Memo/Info.plist
Memo/ViewController.swift

スクリーンショット用のメモアプリを追加しました。
Xcode 6.2以降ならシミュレータでメモアプリ+FlickSKKキーボードが使えます。(Xcode 6.1.1はシミュレータのメモアプリ上でFlickSKKキーボードがでません)

add memo app for screenshots

---

FlickSKKKeyboard/SessionView.swift

キーボードを表示する側のアプリの背景が白のときにいまいち分かりづらかったのでボーダーいれます。

add top border on session view

---

FlickSKKKeyboard/KeyHandler.swift
FlickSKKTests/KeyHandlerSpec.swift

辞書登録するときに送り仮名をアルファベットに変換するのを忘れてた。

送りかなありの単語が登録できない不具合を修正

---

FlickSKKKeyboard/KeyButton.swift
FlickSKKKeyboard/KeyboardViewController.swift

KeyButtonに各フリック方向の文字を表示(記号のみ)

---

Common/ja.lproj/Localizable.strings
FlickSKK.xcodeproj/project.pbxproj
FlickSKK/MainMenuViewController.swift
FlickSKKKeyboard/DictionaryCache.swift
FlickSKKKeyboard/KeyboardViewController.swift
FlickSKKKeyboard/SKKDictionary.swift
FlickSKKTests/KeyHandlerBaseSpec.swift

副作用で、学習するたびに辞書全体が再ロードされるようになってしまって効率がよくない。
別のPRで直す。

学習結果のリセットボタンをつける

---

FlickSKKKeyboard/KeyHandler.swift
FlickSKKKeyboard/TextEngine.swift
FlickSKKTests/KeyHandlerKanjiComposeSpec.swift

送り仮名付きの変換結果学習が、送り仮名ごと学習してしまう不具合を修正

---

FlickSKK.xcodeproj/project.pbxproj
FlickSKK/UserDictionaryViewController.swift
FlickSKKKeyboard/AsyncLoader.swift
FlickSKKKeyboard/DictionaryCache.swift
FlickSKKKeyboard/DictionarySettings.swift
FlickSKKKeyboard/KeyboardViewController.swift
FlickSKKKeyboard/SKKDictionary.swift
FlickSKKKeyboard/SKKUserDictionaryFile.swift
FlickSKKTests/KeyHandlerBaseSpec.swift

* SKKDicitonary の責務を分割した
*  AsyncLoader: 辞書の非同期ロード
* DictionaryCache: キャッシュの管理
* DictionarySettings: 辞書のパスの管理
* 辞書のキャッシュを賢くした …
* キーボードで辞書を更新した場合は、キャッシュを無効にしたいようにした

辞書クラスのリファクタリングおよびキャッシュの改善

---

FlickSKKKeyboard/TextEngine.swift

FlickSKKのクラッシュ頻度があがったので、その修正したくて、実機でデバッグ実行した。
その結果、メモリが2MBほどリークしてるっぽい。
KeyboardViewControllerのdeinitがよばれていなかったため、KeyboardViewController もしくは SKKDelegate を weakなしで参照しているTextEngineを、それをweak参照に変更した。
導入されたのが https://github.com/codefirst/FlickSKK/pull/30 なので、1.2.0には影響ないはず。

SKKDelegateに対する循環参照が発生し、メモリリークしていたので修正

---

FlickSKKKeyboard/KeyHandler.swift
FlickSKKTests/KeyHandlerKanaComposeSpec.swift

▽モードで文字が空になったら、▽モードを抜けるようにした

---

FlickSKK.xcodeproj/project.pbxproj
FlickSKKKeyboard/EntryParser.swift
FlickSKKKeyboard/SKKUserDictionaryFile.swift
FlickSKKTests/SKKDictionaryUserFileSpec.swift

https://github.com/codefirst/FlickSKK/issues/91 の対応です。
なおエスケープにはいくつかのスタイルがある。
*  L辞書: elispでエスケープする。 例: ao /(concat "and\057or")/
* AquaSKK: [xx]でエスケープする。例: foo /foo[2f]/
よりシンプルなAquaSKKスタイルを採用した。

/などの辞書のエントリに使えない文字をエスケープするようにした

---

FlickSKKKeyboard/EntryParser.swift
FlickSKKTests/SKKDictionaryUserFileSpec.swift

1. 「じまえ」を「自前」で変換する
2. 「じまえ」を「時前」で変換する
3. 「じまえ」を「自前」で変換する
変換候補が「時前」「自前」の順番になる。
変換候補が「自前」「時前」の順番になる。
登録済の単語を再登録しようとした場合、並び順が変化しないため。

同じ読みの単語を複数個学習しても、最後の学習結果が先頭に来ない不具合の修正

---

FlickSKK.xcodeproj/project.pbxproj
FlickSKK/Info.plist
FlickSKKKeyboard/Candidate.swift
FlickSKKKeyboard/ComposeMode.swift
FlickSKKKeyboard/ComposeModeFactory.swift
FlickSKKKeyboard/ComposeModePresenter.swift
FlickSKKKeyboard/DictionaryCache.swift
FlickSKKKeyboard/DictionaryEngine.swift
FlickSKKKeyboard/DictionarySettings.swift
FlickSKKKeyboard/KeyHandler.swift
FlickSKKKeyboard/SKKDictionary.swift
FlickSKKKeyboard/SKKUserDictionaryFile.swift
FlickSKKKeyboard/TextEngine.swift
FlickSKKKeyboard/Utilities.swift
FlickSKKTests/ComposeModePresenterSpec.swift
FlickSKKTests/DictionaryEngineSpec.swift
FlickSKKTests/KeyHandlerBaseSpec.swift
FlickSKKTests/KeyHandlerKanaComposeSpec.swift
FlickSKKTests/KeyHandlerKanjiComposeSpec.swift
FlickSKKTests/KeyHandlerWordRegisterWithKanaComposeSpec.swift
FlickSKKTests/SKKDictionaryLocalFileSpec.swift
FlickSKKTests/SKKDictionarySpec.swift
FlickSKKTests/SKKDictionaryUserFileSpec.swift
FlickSKKTests/TextEngineSpec.swift

タブ相当のキー入力はなにをつかうのか?
補完内容
* ユーザー辞書 (履歴) から
* 見出し語から?

タブでダイナミック補完する

---

FlickSKKKeyboard/KeyboardViewController.swift

半角カナ入力モードでは鉤括弧や句読点も半角になってほしい気がするのですがどうでしょうか。

半角カナ入力モードでは記号も半角にする

---

Common/EntryParser.swift
Common/LoadLocalDictionary.swift
Common/ja.lproj/Localizable.strings
FlickSKK.xcodeproj/project.pbxproj
FlickSKK/DownloadDictionary.swift
FlickSKK/ValidateDictionary.swift
FlickSKKTests/EntryParserSpec.swift
FlickSKKTests/LoadLocalDictionarySpec.swift

#116 での残作業です。
辞書エントリとして読みこめない行がある場合は、エラーをだすようにしました。

追加辞書を追加する前に妥当性チェックを行なうようにした

---

FlickSKK.xcodeproj/project.pbxproj
FlickSKKKeyboard/SessionView.swift

絵文字でもダイナミック補完候補であることが分かるように半透明表示にする

---

FlickSKK/Info.plist
FlickSKKKeyboard/Info.plist
FlickSKKKeyboard/KeyButton.swift
Memo/Info.plist

workaround for #152 
iOS 10 GMが来る前に準備しておきます。
1.4.1から余計な変更が入らないように↓のような環境にしてビルドしてますが，古すぎてキツいかもです。
* rbenv local 2.2.3
* gem install cocoapods -v 0.37.2
* pod _0.37.2_ install
* Archive on Xcode 6.4
バージョン1.4.2はTestFlightで，主に3D Touchのために使っていたので，欠番とします。

Fix iOS 10 flick popup performance

---

Common/ThemeColor.swift
FlickSKK.xcodeproj/project.pbxproj
FlickSKK.xcodeproj/xcshareddata/xcschemes/FlickSKK.xcscheme
FlickSKK.xcodeproj/xcshareddata/xcschemes/FlickSKKKeyboard.xcscheme
FlickSKK.xcodeproj/xcshareddata/xcschemes/Memo.xcscheme
FlickSKK/HeadUpProgressViewController.swift
FlickSKKKeyboard/ComposeModePresenter.swift
FlickSKKKeyboard/KeyboardViewController.swift
FlickSKKKeyboard/SKKDelegate.swift
FlickSKKKeyboard/SKKEngine.swift
FlickSKKTests/ComposeModePresenterSpec.swift
FlickSKKTests/MockDelegate.swift
FlickSKKTests/SKKEngineSpec.swift
Podfile
Podfile.lock

iOS 13以上ならsetMarkedTextが使えるのでバージョン分岐とlegacyStyleTextを削除

サポートをiOS 13以上にする
